;/*FB_PKG_DELIM*/

__d("AdsLWISpecOverrideUtils",["Base64"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return r("Base64").encode(JSON.stringify(e))}function s(e){return r("Base64").encode(JSON.stringify(e,function(e,t){if(t!=null)return t}))}l.encodeLWIClientSpecOverride=e,l.encodeLWIClientSpecOverrideDropNullish=s}),98);
__d("IsBoostIGStoriesInItemPickerEnabled.relayprovider",["qex"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("qex")._("696")===!0}};l.default=e}),98);
__d("IsLWIConsistenceExperimentEnabled.relayprovider",[],(function(t,n,r,o,a,i){"use strict";var e={get:function(t){return t===void 0&&(t=!1),!0}};i.default=e}),66);
__d("IsFBAdsExperience.relayprovider",["IsLWIConsistenceExperimentEnabled.relayprovider","gkx","qex"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(t){return t===void 0&&(t=!1),r("IsLWIConsistenceExperimentEnabled.relayprovider").get(t)?t?r("qex")._("349")===!0:r("qex")._("1433")===!0:!r("gkx")("21034")}};l.default=e}),98);
__d("IsFBIGFeaturesIncludedInIGInfra.relayprovider",[],(function(t,n,r,o,a,i){"use strict";var e={get:function(){return!0}};i.default=e}),66);
__d("IsIGInfraUnificationEnabled.relayprovider",[],(function(t,n,r,o,a,i){"use strict";var e={get:function(){return!0}};i.default=e}),66);
__d("IsMBSAdsExperience.relayprovider",["IsLWIConsistenceExperimentEnabled.relayprovider","gkx","qex"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(t){return t===void 0&&(t=!1),r("IsLWIConsistenceExperimentEnabled.relayprovider").get(t)?t?r("qex")._("635")===!0:r("qex")._("1434")===!0:r("gkx")("21034")}};l.default=e}),98);
__d("BizKitAdsGating.entrypointutils",["IsBoostIGStoriesInItemPickerEnabled.relayprovider","IsFBAdsExperience.relayprovider","IsFBIGFeaturesIncludedInIGInfra.relayprovider","IsIGInfraUnificationEnabled.relayprovider","IsLWIConsistenceExperimentEnabled.relayprovider","IsMBSAdsExperience.relayprovider","gkx","qex"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return e===void 0&&(e=!0),r("IsMBSAdsExperience.relayprovider").get(e)}function s(e){return e===void 0&&(e=!0),r("IsFBAdsExperience.relayprovider").get(e)}function u(){return r("gkx")("21034")}function c(){return u()?!0:r("IsLWIConsistenceExperimentEnabled.relayprovider").get()!==!0?!1:r("qex")._("56")===!0}function d(){return s()&&e()}function m(){return r("IsIGInfraUnificationEnabled.relayprovider").get()}function p(){return r("IsBoostIGStoriesInItemPickerEnabled.relayprovider").get()}function _(){return r("IsFBIGFeaturesIncludedInIGInfra.relayprovider").get()}function f(){return r("gkx")("21034")||g()}function g(){return r("IsLWIConsistenceExperimentEnabled.relayprovider").get()!==!0?!1:r("qex")._("108")===!0}l.getIsBizWebAdsExperience=e,l.getIsFBAdsExperience=s,l.getIsBCPEnabledForBizWeb=u,l.getIsBCPRedirectionEnabled=c,l.getIsFBAndBizWebAdsExperience=d,l.getIsIGInfraUnificationEnabled=m,l.getIsBoostIGStoriesInLWIEnabled=p,l.getIsFBIGFeaturesIncludedInIGInfra=_,l.getShouldEnableScheduleAd=f}),98);
__d("FBNucleusArrowDiagonalRightUpFilled16Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 16 16",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M5.75 2.758c.77 0 1.568-.002 2.376-.004 1.215-.003 2.45-.006 3.629-.002a1.499 1.499 0 0 1 1.494 1.498v6.003a1 1 0 1 1-2 0V8.11l.001-1.946-7.793 7.793a1 1 0 0 1-1.414-1.414L9.835 4.75l-1.694.004c-.808.002-1.61.004-2.391.004a1 1 0 1 1 0-2z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=16,u._isSVG=!0;var c=u;l.default=c}),98);
__d("FBNucleusMegaphoneFilled16Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 16 16",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M15 2.505C15 1.149 13.524.308 12.358.999L8.532 3.266A5.25 5.25 0 0 1 5.856 4H3.5a3 3 0 0 0 0 6h2.356a5.25 5.25 0 0 1 2.676.733L12.358 13c1.166.692 2.642-.15 2.642-1.505v-8.99z"}),s.jsx("path",{d:"M5.855 11H3.5c-.278 0-.548-.028-.81-.082l.677 2.86a1.588 1.588 0 0 0 3.133-.366V11.05a4.245 4.245 0 0 0-.645-.05z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=16,u._isSVG=!0;var c=u;l.default=c}),98);
__d("FDSUnitHeaderIconAction.react",["FDSIcon.react","FDSPressable.react","FDSUnitHeaderConstants","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e=["disabled","emphasized","icon","linkProps","onFocusVisibleChange","onHoverIn","onHoverOut","onPress","onPressIn","onPressOut","ref","testid","testOnly_actionPressed"],s,u=s||(s=o("react"));function c(t){var n=o("react-compiler-runtime").c(32),a,i,l,s,c,d,m,p,_,f,g,h,y,C;n[0]!==t?(g=t.disabled,h=t.emphasized,i=t.icon,l=t.linkProps,s=t.onFocusVisibleChange,c=t.onHoverIn,d=t.onHoverOut,m=t.onPress,p=t.onPressIn,_=t.onPressOut,f=t.ref,C=t.testid,y=t.testOnly_actionPressed,a=babelHelpers.objectWithoutPropertiesLoose(t,e),n[0]=t,n[1]=a,n[2]=i,n[3]=l,n[4]=s,n[5]=c,n[6]=d,n[7]=m,n[8]=p,n[9]=_,n[10]=f,n[11]=g,n[12]=h,n[13]=y,n[14]=C):(a=n[1],i=n[2],l=n[3],s=n[4],c=n[5],d=n[6],m=n[7],p=n[8],_=n[9],f=n[10],g=n[11],h=n[12],y=n[13],C=n[14]);var b=g===void 0?!1:g,v=h===void 0?!1:h,S=y!=null?y:!1,R=b?"disabled":v?"primary":"primaryDeemphasizedButtonIcon",L;n[15]!==i||n[16]!==R?(L=u.jsx(r("FDSIcon.react"),{color:R,icon:i,size:16}),n[15]=i,n[16]=R,n[17]=L):L=n[17];var E;return n[18]!==a||n[19]!==b||n[20]!==l||n[21]!==s||n[22]!==c||n[23]!==d||n[24]!==m||n[25]!==p||n[26]!==_||n[27]!==f||n[28]!==S||n[29]!==L||n[30]!==C?(E=u.jsx(r("FDSPressable.react"),babelHelpers.extends({},a,{disabled:b,linkProps:l,onFocusVisibleChange:s,onHoverIn:c,onHoverOut:d,onPress:m,onPressIn:p,onPressOut:_,overlayOffset:o("FDSUnitHeaderConstants").ACTION_TEXT_OVERLAY_OFFSET,overlayRadius:o("FDSUnitHeaderConstants").ACTION_TEXT_OVERLAY_RADIUS,ref:f,testOnly_pressed:S,testid:void 0,children:L})),n[18]=a,n[19]=b,n[20]=l,n[21]=s,n[22]=c,n[23]=d,n[24]=m,n[25]=p,n[26]=_,n[27]=f,n[28]=S,n[29]=L,n[30]=C,n[31]=E):E=n[31],E}l.default=c}),98);
__d("ProfilePlusIntegratedOnboardingAdInterceptDialogQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24546421258291682"}),null);
__d("ProfilePlusIntegratedOnboardingAdInterceptDialogQuery.graphql",["ProfilePlusIntegratedOnboardingAdInterceptDialogQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e=[{defaultValue:null,kind:"LocalArgument",name:"surface"}],t=[{alias:null,args:null,concreteType:"LWIAPI",kind:"LinkedField",name:"lwi",plural:!1,selections:[{alias:null,args:[{kind:"Variable",name:"surface",variableName:"surface"}],concreteType:"XFBIntegratedOnboarding",kind:"LinkedField",name:"integrated_onboarding_data",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"cta_list",storageKey:null}],storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:e,kind:"Fragment",metadata:null,name:"ProfilePlusIntegratedOnboardingAdInterceptDialogQuery",selections:t,type:"Query",abstractKey:null},kind:"Request",operation:{argumentDefinitions:e,kind:"Operation",name:"ProfilePlusIntegratedOnboardingAdInterceptDialogQuery",selections:t},params:{id:n("ProfilePlusIntegratedOnboardingAdInterceptDialogQuery_facebookRelayOperation"),metadata:{},name:"ProfilePlusIntegratedOnboardingAdInterceptDialogQuery",operationKind:"query",text:null}}})();a.exports=e}),null);
__d("XCometLWIConsolidatedProductCreationControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/ad_center/create/consolidatedad/",Object.freeze({show_boost_existing_content:!1}),void 0),s=e;l.default=s}),98);
__d("XCometLWIProductPickerControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/ad_center/create/ad/",Object.freeze({use_template_post:!1}),void 0),s=e;l.default=s}),98);
__d("idToLWIAssetID.entrypointutils",[],(function(t,n,r,o,a,i){"use strict";var e=function(t){return t==null?null:{id:t}},l=e;i.default=l}),66);