;/*FB_PKG_DELIM*/

__d("CometGroupRulesContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9847255165329959"}),null);
__d("CometGroupRulesContentQuery$Parameters",["CometGroupRulesContentQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometGroupRulesContentQuery_facebookRelayOperation"),metadata:{},name:"CometGroupRulesContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometGroupRulesRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9870533602990282"}),null);
__d("CometGroupRulesRootQuery$Parameters",["CometGroupRulesRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometGroupRulesRootQuery_facebookRelayOperation"),metadata:{},name:"CometGroupRulesRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometGroupRulesRoot.entrypoint",["CometGroupRulesContentQuery$Parameters","CometGroupRulesRootQuery$Parameters","JSResourceForInteraction","buildCometGroupAdminToolsPageRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometGroupAdminToolsPageRoute.entrypoint")(r("JSResourceForInteraction")("CometGroupRulesRoot.react").__setRef("CometGroupRulesRoot.entrypoint"),function(e){var t=e.routeProps.groupID;return{queries:{rulesContentQueryReference:{parameters:n("CometGroupRulesContentQuery$Parameters"),variables:{groupID:t}},rulesRootQueryReference:{parameters:n("CometGroupRulesRootQuery$Parameters"),variables:{groupID:t}}}}});l.default=e}),98);
__d("GroupsCometAAV5RootGroupsContainerQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27426215736998032"}),null);
__d("GroupsCometAAV5RootGroupsContainerQuery$Parameters",["GroupsCometAAV5RootGroupsContainerQuery_facebookRelayOperation","groups_comet_use_glv.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometAAV5RootGroupsContainerQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometAAV5RootGroupsContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__groups_comet_use_glvrelayprovider:n("groups_comet_use_glv.relayprovider")}}};a.exports=e}),null);
__d("GroupsCometAAV5Root.entrypoint",["GroupsCometAAV5RootGroupsContainerQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGroupAdminToolsPageRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometGroupAdminToolsPageRoute.entrypoint")(r("JSResourceForInteraction")("GroupsCometAAV5RootGroupsContainer.react").__setRef("GroupsCometAAV5Root.entrypoint"),function(e){var t=e.routeParams,r=e.routeProps.groupID;return{extraProps:t,queries:{queryRef:{parameters:n("GroupsCometAAV5RootGroupsContainerQuery$Parameters"),variables:{automationTargetID:r,expandedCategory:t.expanded_category,scale:o("WebPixelRatio").get(),timeFilter:"TODAY"}}}}});l.default=e}),98);
__d("GroupsCometExpertiseBadgeRequestsRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26928299496842338"}),null);
__d("GroupsCometExpertiseBadgeRequestsRootQuery$Parameters",["GroupsCometExpertiseBadgeRequestsRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometExpertiseBadgeRequestsRootQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometExpertiseBadgeRequestsRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometExpertiseBadgeRequestsRoot.entrypoint",["GroupsCometExpertiseBadgeRequestsRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGroupAdminToolsPageRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometGroupAdminToolsPageRoute.entrypoint")(r("JSResourceForInteraction")("GroupsCometExpertiseBadgeRequestsRoot.react").__setRef("GroupsCometExpertiseBadgeRequestsRoot.entrypoint"),function(e){var t=e.routeProps.groupID;return{queries:{queryRef:{parameters:n("GroupsCometExpertiseBadgeRequestsRootQuery$Parameters"),variables:{groupID:t,scale:o("WebPixelRatio").get()}}}}});l.default=e}),98);
__d("GroupsCometRoleManagementRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="30266799999585403"}),null);
__d("GroupsCometRoleManagementRootQuery$Parameters",["GroupsCometRoleManagementRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometRoleManagementRootQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometRoleManagementRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometRoleManagementRoot.entrypoint",["GroupsCometRoleManagementRootQuery$Parameters","JSResourceForInteraction","buildCometGroupAdminToolsPageRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometGroupAdminToolsPageRoute.entrypoint")(r("JSResourceForInteraction")("GroupsCometRoleManagementRoot.react").__setRef("GroupsCometRoleManagementRoot.entrypoint"),function(e){var t=e.routeProps.groupID;return{queries:{roleManagementQueryRef:{parameters:n("GroupsCometRoleManagementRootQuery$Parameters"),variables:{groupID:t}}}}});l.default=e}),98);
__d("IntegrityHubProfileStatusRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27426268233635704"}),null);
__d("IntegrityHubProfileStatusRootQuery$Parameters",["IntegrityHubProfileStatusRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("IntegrityHubProfileStatusRootQuery_facebookRelayOperation"),metadata:{},name:"IntegrityHubProfileStatusRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("IntegrityHubGroupStatusRoot.entrypoint",["IntegrityHubProfileStatusRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGroupAdminToolsPageRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometGroupAdminToolsPageRoute.entrypoint")(r("JSResourceForInteraction")("IntegrityHubProfileStatusRoot.react").__setRef("IntegrityHubGroupStatusRoot.entrypoint"),function(e){return{queries:{queryReference:{parameters:r("IntegrityHubProfileStatusRootQuery$Parameters"),variables:{profile_id:e.routeProps.groupID,scale:o("WebPixelRatio").get()}}}}});l.default=e}),98);
__d("IntegrityHubProfileStatusRoot.entrypoint",["IntegrityHubProfileStatusRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{queryReference:{parameters:r("IntegrityHubProfileStatusRootQuery$Parameters"),variables:{profile_id:t.routeProps.profile_id,scale:o("WebPixelRatio").get()}}}}},root:r("JSResourceForInteraction")("IntegrityHubProfileStatusRoot.react").__setRef("IntegrityHubProfileStatusRoot.entrypoint")};l.default=e}),98);
__d("LWICometGroupCreationRootContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27176694645320789"}),null);
__d("LWICometGroupCreationRootContentQuery$Parameters",["LWICometGroupCreationRootContentQuery_facebookRelayOperation","LWICometIGUserIdDoubleWriteEnabled.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("LWICometGroupCreationRootContentQuery_facebookRelayOperation"),metadata:{},name:"LWICometGroupCreationRootContentQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__LWICometIGUserIdDoubleWriteEnabledrelayprovider:n("LWICometIGUserIdDoubleWriteEnabled.relayprovider")}}};a.exports=e}),null);
__d("LWICometGroupCreationRoot.entrypoint",["JSResourceForInteraction","LWICometGroupCreationRootContentQuery$Parameters","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeParams.so!=null?String(t.routeParams.so):null,r=String(t.routeParams.page_id),a={ad_account_id:t.routeParams.ad_account_id,boost_id:t.routeParams.boost_id,client_spec_override:e,page_id:r,product:"BOOSTED_GROUP",target_id:t.routeParams.target_id};return{queries:{creationRootQueryReference:{parameters:n("LWICometGroupCreationRootContentQuery$Parameters"),variables:{input:a,scale:o("WebPixelRatio").get()}}}}},root:r("JSResourceForInteraction")("LWICometGroupCreationRoot.react").__setRef("LWICometGroupCreationRoot.entrypoint")};l.default=e}),98);